version: "3"

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true" # Dashboard habilitado pero inseguro (solo para desarrollo)
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:81" # Cambiado a puerto 81
      - "--entrypoints.websecure.address=:443"
    ports:
      - "81:81" # Mapeado el puerto 81
      - "443:443"
      - "8081:8080" # Dashboard de Traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      - VITE_SECRET_KEY=${VITE_SECRET_KEY}
      - VITE_API_KEY=${VITE_API_KEY}
    networks:
      - app-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

networks:
  app-network:
    driver: bridge
